---
default_istio_image_tag: "0.7.1"
default_istio_namespace: "istio-system"
default_istio_jaeger_image_tag: "1.4.1"
default_istio_jaeger_productised_image_tag: "0.6"

openshift_istio_image_dict:
  origin:
    prefix: "openshiftistio/"
    suffix: "-centos7"
    version: "{{ default_istio_image_tag }}"
    namespace: "{{ default_istio_namespace }}"
    jaeger_version: "{{ default_istio_jaeger_image_tag }}"
  openshift-enterprise:
    prefix: "openshift3-istio-tech-preview/"
    suffix: ""
    version: "{{ default_istio_image_tag }}"
    namespace: "{{ default_istio_namespace }}"
    jaeger_version: "{{ default_istio_jaeger_productised_image_tag }}"

openshift_deployment_type: "origin"

openshift_istio_install: true
openshift_istio_install_community: false
openshift_istio_install_auth: false
openshift_istio_install_launcher: false
openshift_client_binary: "/usr/bin/oc --config=/etc/origin/master/admin.kubeconfig"

openshift_istio_service_accounts:
  - "istio-ca-service-account"
  - "istio-ingress-service-account"
  - "istio-mixer-service-account"
  - "istio-mixer-validator-service-account"
  - "istio-pilot-service-account"
  - "istio-sidecar-injector-service-account"

openshift_istio_grafana_service_account: "grafana"
openshift_istio_prometheus_service_account: "prometheus"
openshift_istio_jaeger_service_account: "jaeger"

openshift_istio_additional_scc_service_accounts:
  - "{{ openshift_istio_grafana_service_account }}"
  - "{{ openshift_istio_prometheus_service_account }}"

openshift_istio_additional_scc_privileged_service_accounts:
  - "{{ openshift_istio_jaeger_service_account }}"

openshift_istio_sidecar_service: "istio-sidecar-injector"
openshift_istio_sidecar_secret: "sidecar-injector-certs"

openshift_istio_api_url: "https://{{ ansible_env.KUBERNETES_SERVICE_HOST + ':' + ansible_env.KUBERNETES_SERVICE_PORT }}"

launcher_project_name: devex
launcher_keycloak_url:
launcher_keycloak_realm:
launcher_catalog_git_repo: https://github.com/fabric8-launcher/launcher-booster-catalog.git
launcher_catalog_git_branch: master
launcher_booster_catalog_filter: booster.mission.metadata.istio

launcher_github_username:
launcher_github_token:
launcher_openshift_user: developer
launcher_openshift_pwd: developer

launcher_backend_image_tag: ab535bc
launcher_frontend_image_tag: 4571dfc
launcher_controller_image_tag: 2.3.7
